"""empty message

Revision ID: 8f25d264090
Revises: None
Create Date: 2015-05-14 11:14:39.692444

"""

# revision identifiers, used by Alembic.
revision = '8f25d264090'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bibcode', sa.String(), nullable=False),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('vector_low', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clustering_bibcode'), 'clustering', ['bibcode'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('members', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('centroid', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_cluster'), 'clusters', ['cluster'], unique=False)
    op.create_table('coreads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bibcode', sa.String(), nullable=False),
    sa.Column('coreads', postgresql.JSON(), nullable=True),
    sa.Column('readers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coreads_bibcode'), 'coreads', ['bibcode'], unique=False)
    op.create_table('reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cookie', sa.String(), nullable=False),
    sa.Column('reads', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reads_cookie'), 'reads', ['cookie'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reads_cookie'), table_name='reads')
    op.drop_table('reads')
    op.drop_index(op.f('ix_coreads_bibcode'), table_name='coreads')
    op.drop_table('coreads')
    op.drop_index(op.f('ix_clusters_cluster'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_clustering_bibcode'), table_name='clustering')
    op.drop_table('clustering')
    ### end Alembic commands ###
